#!/bin/bash
[[ -f ./setup ]] && source ./setup

MOSQUITTO_OWNER=${MOSQUITTO_OWNER:-"root"}

pushd /root > /dev/null
    exec su-exec ${MOSQUITTO_OWNER} mosquitto -c /etc/mosquitto/mosquitto.conf
popd
